Improvements for es.json
PretendoNetwork/juxt-web pull request #12
Opened 2021-08-31 12:40 UTC by Angel3245

- Grammatical and spelling errors fixed

2021-08-31 14:46 UTC, CarlosNunezMX reviewed
"Mola" is a traduction for the Spanish for Spain but in latam doesn't use it, because i put "Yeahs"

2021-08-31 14:52 UTC, CarlosNunezMX requested changes
But i i think on Change "mola" for "Genial" or "Me gusta"

2021-08-31 16:08 UTC, DkStar7 commented
Sounds great to me, but I would change the part where it says "Mostrar ____ en Perfil" to "Mostrar ____ en tu perfil". Además de cambiar "anuncios" to "noticias" Apart from that, the translation is perfect for me.

2021-08-31 16:21 UTC, DkStar7 reviewed
It's a small change. Apart from that, the translation is perfect.

2021-08-31 17:08 UTC, CarlosNunezMX commented on src/translations/es.json
>      "show_country": "Mostrar país en Perfil",
Sounds great

2021-08-31 20:41 UTC, Angel3245 commented on src/translations/es.json
>      "show_country": "Mostrar país en Perfil",
Okay, i'll change it.

2021-08-31 20:58 UTC, Angel3245 commented
> But i i think on Change "mola" for "Genial" or "Me gusta"

I wrote "Mola" because it's the official translation for that on Miiverse, but "Genial" or "Me gusta" are also okay.

2021-08-31 21:01 UTC, CarlosNunezMX commented
> > But i i think on Change "mola" for "Genial" or "Me gusta"
> 
> I wrote "Mola" because it's the official translation for that on Miiverse, but "Genial" or "Me gusta" are also okay.

Yep or "Me gusta" is a common expression on Latam and Spain.

2021-09-01 16:04 UTC, DkStar7 commented
You can change "página personal" by "perfil"

2021-09-03 17:45 UTC, merged